name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.3
  - blas=1.0
  - boltons=23.0.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - conda=24.3.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - distro=1.8.0
  - expat=2.5.0
  - fmt=10.2.1
  - icu=73.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jsonpointer=2.1
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.38
  - libarchive=3.7.2
  - libcurl=8.7.1
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libiconv=1.17
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libpq=16.2
  - libsolv=0.7.24
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - menuinst=2.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.2.1
  - pandas=2.2.1
  - pcre2=10.42
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - psycopg2=2.9.9
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2023.3.post1
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.13
  - tqdm=4.65.0
  - truststore=0.8.0
  - tzdata=2023d
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - attrs==23.2.0
      - cachetools==5.3.3
      - dataclasses-json==0.6.4
      - discord-py==2.3.2
      - frozenlist==1.4.1
      - google-api-core==2.17.1
      - google-api-python-client==2.129.0
      - google-auth==2.29.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.0
      - googleapis-common-protos==1.63.0
      - greenlet==3.0.3
      - gspread==6.1.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httplib2==0.22.0
      - httpx==0.27.0
      - json-log-formatter==1.0
      - jsonpatch==1.33
      - langchain==0.1.13
      - langchain-community==0.0.29
      - langchain-core==0.1.36
      - langchain-text-splitters==0.0.1
      - langsmith==0.1.36
      - marshmallow==3.21.1
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - openai==1.28.1
      - orjson==3.10.0
      - packaging==23.2
      - protobuf==4.25.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pyparsing==3.1.2
      - python-dotenv==1.0.1
      - pyyaml==6.0.1
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - slack-sdk==3.27.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.29
      - strenum==0.4.15
      - tenacity==8.2.3
      - typing-extensions==4.10.0
      - typing-inspect==0.9.0
      - uritemplate==4.1.1
      - yarl==1.9.4
